#
# CircleCI 2.0
#
version: 2
jobs:
  package:
    docker:
      - image: circleci/python
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: Package
          command: |
            ./package.sh ${CIRCLE_PROJECT_USERNAME} ${CIRCLE_PROJECT_REPONAME}
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - target/*
  publish:
    docker:
      - image: opspresso/awscli
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Publish
          command: |
            aws s3 sync workspace/target/ s3://repo.opsnow.io/${CIRCLE_PROJECT_REPONAME}/ --acl public-read
  release:
    docker:
      - image: circleci/golang
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Release
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(cat workspace/target/VERSION)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} workspace/target/dist/
  slack:
    docker:
      - image: circleci/python
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Notification
          command: |
            VERSION="$(cat workspace/target/VERSION)"
            FOOTER="<https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}|${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}>"
            workspace/target/slack --token="${SLACK_TOKEN}" \
                --emoji=":construction_worker:" --username="valve" \
                --color="good" --title="${CIRCLE_PROJECT_REPONAME} updated" --footer="${FOOTER}" "\`${VERSION}\`"

workflows:
  version: 2
  apply:
    jobs:
      - package
      - publish:
          requires:
            - package
      - release:
          requires:
            - package
      - slack:
          requires:
            - release
