# chart-repo: stable/chartmuseum
# chart-version: 1.9.0

fullnameOverride: chartmuseum

env:
  open:
    DISABLE_API: false

ingress:
  enabled: true
  hosts:
    chartmuseum.127.0.0.1.nip.io:
      - /
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m
